tapas: fix build failure due to non-existent file
and add missing system_dlm modules.load

FileExistsError: [Errno 17] File exists: 'out/target/product/tapas/vendor_dlkm/lib/modules/modules.blocklist' -> 'out/target/product/tapas/tmp9219be9k/lib/modules/modules.blocklist'

Signed-off-by: Ali Hasan <ahb7671@gmail.com>